### ISSUE TITLE
[FR]: AGPL Missing

### ISSUE THREAD

**Issue by HemantSachdeva** [minherz/copyright-inserter#15]
### Contact Details

hemant.evolver@gmail.com

### What do you propose?

1. I am planning to make a PR for adding AGPL v3 license, may I sort the description and licenses in the list/array or just append the license at the end?

2. Plugin version 1.0.10 is also missing in the Issue template (I can also include in PR if you want.)

**Comment by minherz** [comment]
No need to add the new version to the template. I have changed the template to use a string field instead. Thank you for pointing out the problem.

**Comment by HemantSachdeva** [comment]
> No need to add the new version to the template. I have changed the template to use a string field instead. Thank you for pointing out the problem.

Okay but what about the 1st query about sorting or appending the AGPL v3 licence?

**Comment by HemantSachdeva** [comment]
IMO appending Licence to the end would look ugly in later versions if we take a case of having inclusion of all the Open-source Licenses

**Comment by minherz** [comment]
Feel free to propose the change. I am not sure what you mean by sorting though. Also "ugly" like "beauty" are in the eyes of beholder 🙂

**Comment by HemantSachdeva** [comment]
Have a look at #16 

And yeah you are right about the beauty thing. I was just going a bit more techie xD.
