### ISSUE TITLE
[FR]: Add translation of copyright message in italian

### ISSUE THREAD

**Issue by NicolasGirondi** [minherz/copyright-inserter#21]
### Contact Details

nicolas.girondi@gmail.com

### Plugin Version

1.0.13

### What do you propose?

Hello. I would like to translate the copyright message created with the command in Italian. There's just one problem: i dont't know how it's generated, so you should add an option to set the message language (i.e. a dropdown list in the plugin settings section containing all the completed translation languages and the option "default"), then you should tell me where are the files and the sentences to translate. I hope to be helpful.

**Comment by minherz** [comment]
Hi @NicolasGirondi , thank you for your proposal. I have looked into what different license agreements have to say about non-english license translations. I checked several holders (e.g. [gnu][] and [apache][]) and all of them claim that _only english_ version should be present as officially valid one. The text in other languages can be added to documentation for convenience.
Following these findings, I do not see reasonable to implement copyright headers in non-english languages in source files.
Another problem is in achieving a correct and not amateur translation of the license texts to other languages. Only couple of licenses provided such texts and I did not find one in Italian. I would like to avoid distributing unofficial and  potentially harmful license agreements.
Given these considerations, I have to reject this feature request. I hope you can understand my reasoning.

[gnu]: https://www.gnu.org/licenses/translations.html
[apache]: https://www.apache.org/foundation/license-faq.html#Translation
