### ISSUE TITLE
[BUG]: How do you configure this (I am probably stupid but I don't see it)

### ISSUE THREAD

**Issue by colabogey** [minherz/copyright-inserter#23]
### Contact Details

colabogey@protonmail.com

### Plugin Version

1.0.14

### What happened?

I tried it out.
Pretty cool.
But I don't want the default license stuff.
I cannot see how/where to change this.
I am certain it is all me. But maybe you could provide a hint in the extension info

### What did you expect to happened?

I wanted GPL not google
can't figure it out

**Comment by colabogey** [comment]
I used a find and sed to accomplish this. 
So please disregard.
Thanks

**Comment by minherz** [comment]
Hi @colabogey , i see that you managed to find the solution already. I am not sure why you had to use sed though. Just to be sure that we are on the same page, this plugin does not allow "custom license stuff". It supports a predefined (built-in) list of the following licenses:

* APACHE 2.0
* BSD
* MIT
* GPL 3.0
* Affero GPL 3.0
* MPL 2.0

The license (by default it uses Apache) is configured in the extension's [settings]. And you should be able to change it as well as few other parameters (e.g. use of block comment vs. line comment). I admit that README is not very informative about it, I will verbalize this in README so it will be easier to understand and to find.

[settings]: https://code.visualstudio.com/docs/getstarted/settings

**Comment by colabogey** [comment]
Thanks for getting back.

I was simply trying to insert a GPL license.
Could not see how to do that instead of the default.

I see the documentation speaks of some form of settings, but I could never 'navigate' to that.

So bottom line, I could not configure it to use one of the 'standard' copyright statements.
Like I mentioned its probably all on me :)

If you feel like it, how do you configure this plug in ?

Thanks again

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by colabogey** [comment]
I got it.
Your email had the link to 'settings' and that led me to the answer.

I knew it was all me :)

Thanks

(I'm done bugging you now :))

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
