### ISSUE TITLE
Support for custom licenses

### ISSUE THREAD

**Issue by sll552** [minherz/copyright-inserter#4]
It would be nice to be able to configure your own license text and not be limited to apache, bsd and mit.

**Comment by minherz** [comment]
Thank you for suggestion. I understand it that the feature request is based on personal needs. I will check whether or not code supports saving the formatted text in the configuration. I suspect that it is able to keep only spaces but not new lines or tabs. It might seriously limit an ability to provide custom license text that is longer than one line.
Do you think this feature will be useful if the custom license text will be one liner?

**Comment by sll552** [comment]
If escape sequences (like '\n') are possible it's no problem if it needs to be one line, which I think is the case because vscode settings is JSON as far as I know. 
Another option would be to read the template from a file?

**Comment by minherz** [comment]
I am afraid your suggestion is not in scope of this extension:
- it should be possible to process `\n` and convert it into a new line but it will be hard to define and format the custom license text
- currently the extension works in both modes: standard and remote. adding custom template file introduces too many failure points and might not work in the remote mode
- the use of custom license text implies there is no need for copyright holder or year which renders the extension to mere clipboard
